version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Run Backend Tests
          command: |
            cd backend
            npm test
      - run:
          name: Run Frontend Tests
          command: |
            cd frontend
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
