version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

workflows:
  version: 2
  build:
    jobs:
      - build
